<x-storefront.account-shell :heading="'Order '.$order->order_number" :intro="'Placed on '.optional($order->placed_at)->format('F j, Y')">
    <div class="flex flex-wrap gap-2"><x-storefront.badge :text="str_replace('_', ' ', $order->financial_status instanceof \BackedEnum ? $order->financial_status->value : $order->financial_status)" /><x-storefront.badge :text="str_replace('_', ' ', $order->fulfillment_status instanceof \BackedEnum ? $order->fulfillment_status->value : $order->fulfillment_status)" /></div>
    <section class="sf-card mt-6" aria-labelledby="order-items-heading"><h2 id="order-items-heading" class="text-xl font-semibold">Items</h2><div class="mt-4 divide-y divide-slate-200 dark:divide-slate-800">@foreach($order->lines as $line)@php($media = optional(optional($line->product)->media->first())->storage_key)<div class="flex items-center gap-4 py-4"><div class="size-16 shrink-0 rounded-xl bg-slate-100 dark:bg-slate-800">@if($media)<img src="{{ Storage::disk('public')->url($media) }}" alt="" class="h-full w-full rounded-xl object-cover">@endif</div><div class="min-w-0 flex-1"><h3 class="font-medium">{{ $line->title_snapshot }}</h3>@if($line->sku_snapshot)<p class="mt-1 text-xs text-slate-500">SKU {{ $line->sku_snapshot }}</p>@endif<p class="mt-1 text-sm text-slate-500">Quantity {{ $line->quantity }}</p></div><strong><x-storefront.price :amount="$line->total_amount" :currency="$order->currency" /></strong></div>@endforeach</div></section>
    @php($shipping = is_string($order->shipping_address_json) ? json_decode($order->shipping_address_json, true) : (array) $order->shipping_address_json)
    @php($billing = is_string($order->billing_address_json) ? json_decode($order->billing_address_json, true) : (array) $order->billing_address_json)
    <div class="mt-6 grid gap-4 md:grid-cols-3"><section class="sf-card"><h2 class="font-semibold">Shipping Address</h2><address class="mt-3 text-sm not-italic leading-6 text-slate-600 dark:text-slate-300">{{ data_get($shipping,'first_name') }} {{ data_get($shipping,'last_name') }}<br>{{ data_get($shipping,'address1') }}<br>{{ data_get($shipping,'zip',data_get($shipping,'postal_code')) }} {{ data_get($shipping,'city') }}<br>{{ data_get($shipping,'country_code',data_get($shipping,'country')) }}</address></section><section class="sf-card"><h2 class="font-semibold">Billing Address</h2><address class="mt-3 text-sm not-italic leading-6 text-slate-600 dark:text-slate-300">{{ data_get($billing,'first_name') }} {{ data_get($billing,'last_name') }}<br>{{ data_get($billing,'address1') }}<br>{{ data_get($billing,'zip',data_get($billing,'postal_code')) }} {{ data_get($billing,'city') }}</address></section><section class="sf-card"><h2 class="font-semibold">Payment</h2><p class="mt-3 text-sm capitalize text-slate-600 dark:text-slate-300">{{ str_replace('_',' ', $order->payment_method instanceof \BackedEnum ? $order->payment_method->value : $order->payment_method) }}</p></section></div>
    <dl class="ml-auto mt-8 max-w-sm space-y-3 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd><x-storefront.price :amount="$order->subtotal_amount" :currency="$order->currency" /></dd></div>@if($order->discount_amount > 0)<div class="flex justify-between text-emerald-700"><dt>Discount</dt><dd>-<x-storefront.price :amount="$order->discount_amount" :currency="$order->currency" /></dd></div>@endif<div class="flex justify-between"><dt>Shipping</dt><dd><x-storefront.price :amount="$order->shipping_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between"><dt>Tax</dt><dd><x-storefront.price :amount="$order->tax_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between border-t border-slate-200 pt-4 text-lg font-semibold dark:border-slate-800"><dt>Total</dt><dd><x-storefront.price :amount="$order->total_amount" :currency="$order->currency" /></dd></div></dl>
    @if($order->fulfillments->isNotEmpty())<section class="sf-card mt-8" aria-labelledby="fulfillment-heading"><h2 id="fulfillment-heading" class="text-xl font-semibold">Fulfillment</h2><div class="mt-4 space-y-4">@foreach($order->fulfillments as $fulfillment)<div class="rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-900"><div class="flex justify-between"><strong class="capitalize">{{ $fulfillment->status instanceof \BackedEnum ? $fulfillment->status->value : $fulfillment->status }}</strong>@if($fulfillment->tracking_url)<a href="{{ $fulfillment->tracking_url }}" target="_blank" rel="noopener noreferrer" class="sf-text-link">Track shipment <span class="sr-only">(opens in a new tab)</span></a>@endif</div>@if($fulfillment->tracking_company)<p class="mt-2 text-slate-500">{{ $fulfillment->tracking_company }} · {{ $fulfillment->tracking_number }}</p>@endif</div>@endforeach</div></section>@endif
</x-storefront.account-shell>
