<div class="space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-4">
        <div><a href="{{ route('admin.orders.index') }}" wire:navigate class="text-sm text-blue-700 hover:underline">← Orders</a><div class="mt-3 flex flex-wrap items-center gap-3"><flux:heading size="xl" level="1">{{ $order->order_number }}</flux:heading><flux:badge :color="$order->financial_status->value === 'paid' ? 'green' : ($order->financial_status->value === 'refunded' ? 'yellow' : 'zinc')">{{ str_replace('_', ' ', ucfirst($order->financial_status->value)) }}</flux:badge><flux:badge :color="$order->fulfillment_status->value === 'fulfilled' ? 'green' : 'zinc'">{{ str_replace('_', ' ', ucfirst($order->fulfillment_status->value)) }}</flux:badge></div><flux:text class="mt-2" variant="subtle">Placed {{ $order->placed_at?->format('M j, Y g:i A') ?? '—' }}</flux:text></div>
        @if ($message)<div role="status" class="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ $message }}</div>@endif
    </div>

    @if ($errors->has('payment') || $errors->has('fulfillment') || $errors->has('fulfillmentLines') || $errors->has('refundAmount'))
        <flux:callout variant="danger" icon="x-circle" heading="Action could not be completed.">
            <ul class="list-disc pl-5">@foreach (['payment', 'fulfillment', 'fulfillmentLines', 'refundAmount'] as $errorKey) @foreach ($errors->get($errorKey) as $error)<li>{{ $error }}</li>@endforeach @endforeach</ul>
        </flux:callout>
    @endif

    <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
        <div class="space-y-6">
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200">
                <div class="flex flex-wrap gap-3">
                    @if ($order->payment_method === 'bank_transfer' && $order->financial_status->value === 'pending')<flux:button variant="primary" wire:click="confirmPayment">Confirm payment</flux:button>@endif
                    @if ($order->fulfillment_status->value !== 'fulfilled')<flux:button wire:click="openFulfillmentModal" :disabled="! in_array($order->financial_status->value, ['paid', 'partially_refunded'], true)">Create fulfillment</flux:button>@endif
                    @if (in_array($order->financial_status->value, ['paid', 'partially_refunded'], true))<flux:button variant="ghost" wire:click="openRefundModal">Refund</flux:button>@endif
                </div>
                @if (! in_array($order->financial_status->value, ['paid', 'partially_refunded'], true))<flux:callout class="mt-5" variant="warning" icon="exclamation-triangle" heading="Cannot create fulfillment.">Payment must be confirmed before items can be fulfilled. Current financial status: {{ $order->financial_status->value }}.</flux:callout>@endif
            </section>

            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200">
                <flux:heading size="lg">Order timeline</flux:heading>
                <ol class="mt-5 space-y-5 border-l border-zinc-200 pl-6">
                    <li class="relative"><span class="absolute -left-[31px] top-1.5 h-2.5 w-2.5 rounded-full bg-blue-600 ring-4 ring-white"></span><p class="font-medium">Order placed</p><p class="text-sm text-zinc-500">{{ $order->placed_at?->format('M j, Y g:i A') ?? '—' }}</p></li>
                    @foreach ($order->payments as $payment)
                        @if ($payment->status->value === 'captured')<li wire:key="payment-event-{{ $payment->id }}" class="relative"><span class="absolute -left-[31px] top-1.5 h-2.5 w-2.5 rounded-full bg-emerald-600 ring-4 ring-white"></span><p class="font-medium">Payment received</p><p class="text-sm text-zinc-500">{{ $payment->updated_at?->format('M j, Y g:i A') }}</p></li>@endif
                    @endforeach
                    @foreach ($order->fulfillments as $fulfillment)
                        <li wire:key="timeline-fulfillment-{{ $fulfillment->id }}" class="relative"><span class="absolute -left-[31px] top-1.5 h-2.5 w-2.5 rounded-full bg-zinc-500 ring-4 ring-white"></span><p class="font-medium">Fulfillment {{ $fulfillment->status }}</p><p class="text-sm text-zinc-500">{{ $fulfillment->updated_at?->format('M j, Y g:i A') }}</p></li>
                    @endforeach
                    @foreach ($order->refunds->where('status', 'processed') as $refund)<li wire:key="timeline-refund-{{ $refund->id }}" class="relative"><span class="absolute -left-[31px] top-1.5 h-2.5 w-2.5 rounded-full bg-amber-500 ring-4 ring-white"></span><p class="font-medium">Refunded {{ $order->currency }} {{ number_format($refund->amount / 100, 2) }}</p><p class="text-sm text-zinc-500">{{ $refund->updated_at?->format('M j, Y g:i A') }}</p></li>@endforeach
                </ol>
            </section>

            <section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-zinc-200">
                <div class="p-6"><flux:heading size="lg">Order lines</flux:heading></div>
                <div class="overflow-x-auto"><table class="min-w-full divide-y divide-zinc-200 text-left text-sm"><thead class="bg-zinc-50"><tr><th class="px-6 py-3">Product</th><th class="px-6 py-3">SKU</th><th class="px-6 py-3">Qty</th><th class="px-6 py-3 text-right">Unit price</th><th class="px-6 py-3 text-right">Total</th></tr></thead><tbody class="divide-y divide-zinc-100">@foreach ($order->lines as $line)<tr wire:key="order-line-{{ $line->id }}"><td class="px-6 py-4"><p class="font-medium">{{ $line->product_title }}</p><p class="text-xs text-zinc-500">{{ $line->variant_title }}</p></td><td class="px-6 py-4 text-zinc-600">{{ $line->sku ?: '—' }}</td><td class="px-6 py-4">{{ $line->quantity }}</td><td class="px-6 py-4 text-right">{{ $order->currency }} {{ number_format($line->unit_price_amount / 100, 2) }}</td><td class="px-6 py-4 text-right font-semibold">{{ $order->currency }} {{ number_format($line->line_total_amount / 100, 2) }}</td></tr>@endforeach</tbody></table></div>
                <dl class="ml-auto max-w-sm space-y-2 border-t border-zinc-200 p-6 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd>{{ $order->currency }} {{ number_format($order->subtotal_amount / 100, 2) }}</dd></div><div class="flex justify-between"><dt>Discount</dt><dd>-{{ $order->currency }} {{ number_format($order->discount_amount / 100, 2) }}</dd></div><div class="flex justify-between"><dt>Shipping</dt><dd>{{ $order->currency }} {{ number_format($order->shipping_amount / 100, 2) }}</dd></div><div class="flex justify-between"><dt>Tax</dt><dd>{{ $order->currency }} {{ number_format($order->tax_amount / 100, 2) }}</dd></div><div class="flex justify-between border-t border-zinc-200 pt-3 text-base font-bold"><dt>Total</dt><dd>{{ $order->currency }} {{ number_format($order->total_amount / 100, 2) }}</dd></div></dl>
            </section>

            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><flux:heading size="lg">Payment details</flux:heading>@forelse ($order->payments as $payment)<div wire:key="payment-{{ $payment->id }}" class="mt-4 grid gap-2 text-sm sm:grid-cols-2"><span>Method: {{ str_replace('_', ' ', ucfirst($payment->method->value)) }}</span><span>Status: <flux:badge :color="$payment->status->value === 'captured' ? 'green' : ($payment->status->value === 'failed' ? 'red' : 'zinc')">{{ ucfirst($payment->status->value) }}</flux:badge></span><span>Amount: {{ $payment->currency }} {{ number_format($payment->amount / 100, 2) }}</span><span>Reference: {{ $payment->provider_payment_id ?: '—' }}</span></div>@empty<p class="mt-4 text-sm text-zinc-500">No payment record exists.</p>@endforelse</section>

            <section class="space-y-4"><flux:heading size="lg">Fulfillments</flux:heading>@forelse ($order->fulfillments as $fulfillment)<article wire:key="fulfillment-{{ $fulfillment->id }}" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><div class="flex flex-wrap items-center justify-between gap-3"><div><flux:badge :color="$fulfillment->status === 'delivered' ? 'green' : ($fulfillment->status === 'shipped' ? 'blue' : 'zinc')">{{ ucfirst($fulfillment->status) }}</flux:badge><p class="mt-2 text-sm text-zinc-600">{{ $fulfillment->tracking_company ?: 'No carrier' }} {{ $fulfillment->tracking_number }}</p></div><div class="flex gap-2">@if ($fulfillment->status === 'pending')<flux:button size="sm" wire:click="markAsShipped({{ $fulfillment->id }})">Mark as shipped</flux:button>@elseif ($fulfillment->status === 'shipped')<flux:button size="sm" variant="primary" wire:click="markAsDelivered({{ $fulfillment->id }})">Mark as delivered</flux:button>@endif</div></div><ul class="mt-4 space-y-1 text-sm text-zinc-600">@foreach ($fulfillment->lines as $fulfillmentLine)<li>{{ $fulfillmentLine->orderLine?->product_title }} × {{ $fulfillmentLine->quantity }}</li>@endforeach</ul>@if ($fulfillment->tracking_url)<a class="mt-3 inline-block text-sm text-blue-700 underline" href="{{ $fulfillment->tracking_url }}" target="_blank" rel="noreferrer">Track shipment</a>@endif</article>@empty<p class="rounded-2xl bg-white p-6 text-sm text-zinc-500 ring-1 ring-zinc-200">No fulfillments yet.</p>@endforelse</section>
        </div>

        <aside class="space-y-6">
            <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><flux:heading size="lg">Customer</flux:heading><div class="mt-4"><p class="font-medium">{{ $order->customer?->name ?: 'Guest' }}</p><p class="text-sm text-zinc-500">{{ $order->customer?->email ?: $order->email }}</p>@if ($order->customer)<a href="{{ route('admin.customers.show', $order->customer) }}" wire:navigate class="mt-3 inline-block text-sm text-blue-700 hover:underline">View customer →</a>@endif</div></section>
            @foreach ([['Shipping address', $order->shipping_address_json], ['Billing address', $order->billing_address_json]] as [$label, $address])<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><flux:heading size="lg">{{ $label }}</flux:heading>@if ($address)<address class="mt-4 space-y-1 text-sm not-italic text-zinc-600"><div>{{ $address['line1'] ?? $address['address1'] ?? '' }}</div><div>{{ $address['line2'] ?? $address['address2'] ?? '' }}</div><div>{{ $address['city'] ?? '' }} {{ $address['state'] ?? $address['province'] ?? '' }} {{ $address['zip'] ?? $address['postal_code'] ?? '' }}</div><div>{{ $address['country'] ?? $address['country_code'] ?? '' }}</div></address>@else<flux:text class="mt-4" variant="subtle">No address provided.</flux:text>@endif</section>@endforeach
        </aside>
    </div>

    <flux:modal name="create-fulfillment" class="max-w-lg" wire:model="showFulfillmentModal">
        <form wire:submit="createFulfillment" class="space-y-6"><flux:heading size="lg">Create fulfillment</flux:heading><div class="space-y-3">@foreach ($order->lines as $line) @if (($fulfillmentLines[$line->id] ?? 0) > 0)<div wire:key="fulfill-form-{{ $line->id }}" class="grid grid-cols-[auto_1fr_100px] items-center gap-3"><input id="fulfill-{{ $line->id }}" type="checkbox" wire:model="selectedFulfillmentLines.{{ $line->id }}" class="rounded border-zinc-300 text-blue-600"><label for="fulfill-{{ $line->id }}" class="text-sm">{{ $line->product_title }} <span class="text-zinc-500">({{ $fulfillmentLines[$line->id] }} available)</span></label><flux:input type="number" min="0" max="{{ $fulfillmentLines[$line->id] }}" wire:model="fulfillmentLines.{{ $line->id }}" aria-label="Quantity for {{ $line->product_title }}" /></div>@endif @endforeach</div><div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="trackingCompany" label="Tracking company" placeholder="UPS, FedEx, DHL…" /><flux:input wire:model="trackingNumber" label="Tracking number" /><flux:input wire:model="trackingUrl" label="Tracking URL" type="url" class="sm:col-span-2" /></div><div class="flex justify-end gap-3"><flux:button type="button" variant="ghost" wire:click="$set('showFulfillmentModal', false)">Cancel</flux:button><flux:button type="submit" variant="primary">Create fulfillment</flux:button></div></form>
    </flux:modal>

    <flux:modal name="create-refund" class="max-w-lg" wire:model="showRefundModal">
        <form wire:submit="createRefund" class="space-y-6"><flux:heading size="lg">Refund order</flux:heading><div class="space-y-3">@foreach ($order->lines as $line)<div wire:key="refund-form-{{ $line->id }}" class="grid grid-cols-[auto_1fr_100px] items-center gap-3"><input id="refund-{{ $line->id }}" type="checkbox" wire:model="selectedRefundLines.{{ $line->id }}" class="rounded border-zinc-300 text-blue-600"><label for="refund-{{ $line->id }}" class="text-sm">{{ $line->product_title }}</label><flux:input type="number" min="0" max="{{ $line->quantity }}" wire:model="refundLines.{{ $line->id }}" aria-label="Quantity to refund for {{ $line->product_title }}" /></div>@endforeach</div><div class="border-t border-zinc-200 pt-5"><flux:input wire:model="refundAmount" label="Custom amount (cents)" type="number" min="1" placeholder="0" /><flux:textarea wire:model="refundReason" label="Reason" rows="3" placeholder="Reason for refund…" class="mt-4" /></div><div class="flex justify-end gap-3"><flux:button type="button" variant="ghost" wire:click="$set('showRefundModal', false)">Cancel</flux:button><flux:button type="submit" variant="danger">Create refund</flux:button></div></form>
    </flux:modal>
</div>
