<x-admin.page :title="$order->order_number" :subtitle="'Placed '.($order->placed_at?->diffForHumans() ?? 'recently')">
    <x-slot:actions>@if($order->payment_method?->value === 'bank_transfer' && $order->financial_status->value === 'pending')<flux:button wire:click="confirmPayment" variant="primary" icon="check-circle">Confirm payment</flux:button>@endif<flux:button wire:click="$set('showRefundModal', true)" icon="arrow-uturn-left">Refund</flux:button></x-slot:actions>
    @if($order->financial_status->value === 'pending')<flux:callout variant="warning" icon="exclamation-triangle" heading="Payment required">This order must be paid before fulfillment can be created.</flux:callout>@endif
    <div class="grid gap-6 xl:grid-cols-3">
        <div class="space-y-6 xl:col-span-2">
            <x-admin.panel heading="Items"><div class="divide-y divide-zinc-200 dark:divide-zinc-800">@foreach($order->lines as $line)<div wire:key="order-line-{{ $line->id }}" class="flex items-start justify-between gap-4 py-4"><div><div class="font-medium">{{ $line->title_snapshot }}</div><div class="text-sm text-zinc-500">SKU {{ $line->sku_snapshot ?: '—' }} · Qty {{ $line->quantity }}</div></div><div class="font-medium">{{ \Illuminate\Support\Number::currency($line->total_amount / 100, in: $order->currency) }}</div></div>@endforeach</div><div class="ms-auto mt-4 grid max-w-sm gap-2 border-t border-zinc-200 pt-4 text-sm dark:border-zinc-800">@foreach(['Subtotal' => $order->subtotal_amount, 'Discount' => -$order->discount_amount, 'Shipping' => $order->shipping_amount, 'Tax' => $order->tax_amount] as $label => $amount)<div class="flex justify-between"><span class="text-zinc-500">{{ $label }}</span><span>{{ \Illuminate\Support\Number::currency($amount / 100, in: $order->currency) }}</span></div>@endforeach<div class="flex justify-between text-base font-semibold"><span>Total</span><span>{{ \Illuminate\Support\Number::currency($order->total_amount / 100, in: $order->currency) }}</span></div></div></x-admin.panel>
            <x-admin.panel heading="Fulfillment"><div class="space-y-3">@forelse($order->fulfillments as $fulfillment)<div wire:key="fulfillment-{{ $fulfillment->id }}" class="rounded-xl border border-zinc-200 p-4 dark:border-zinc-800"><div class="flex flex-wrap items-center justify-between gap-3"><div><flux:badge>{{ str($fulfillment->status->value)->headline() }}</flux:badge><div class="mt-2 text-sm">{{ $fulfillment->tracking_company }} {{ $fulfillment->tracking_number }}</div></div><div class="flex gap-2">@if($fulfillment->status->value === 'pending')<flux:button wire:click="markShipped({{ $fulfillment->id }})" size="sm">Mark as shipped</flux:button>@elseif($fulfillment->status->value === 'shipped')<flux:button wire:click="markDelivered({{ $fulfillment->id }})" size="sm">Mark as delivered</flux:button>@endif</div></div></div>@empty<flux:text>No fulfillments yet.</flux:text>@endforelse@if($order->financial_status->value !== 'pending')<flux:button wire:click="$set('showFulfillmentModal', true)" icon="truck">Create fulfillment</flux:button>@endif</div></x-admin.panel>
            <x-admin.panel heading="Timeline"><ol class="space-y-4 border-s border-zinc-200 ps-5 dark:border-zinc-800"><li><div class="font-medium">Order created</div><div class="text-sm text-zinc-500">{{ $order->placed_at?->format('M j, Y H:i') }}</div></li>@foreach($order->refunds as $refund)<li wire:key="refund-timeline-{{ $refund->id }}"><div class="font-medium">Refund {{ str($refund->status->value)->headline() }}</div><div class="text-sm text-zinc-500">{{ \Illuminate\Support\Number::currency($refund->amount / 100, in: $order->currency) }}</div></li>@endforeach</ol></x-admin.panel>
        </div>
        <div class="space-y-6"><x-admin.panel heading="Status"><div class="space-y-3"><div class="flex justify-between"><span>Payment</span><flux:badge>{{ str($order->financial_status->value)->headline() }}</flux:badge></div><div class="flex justify-between"><span>Fulfillment</span><flux:badge>{{ str($order->fulfillment_status->value)->headline() }}</flux:badge></div></div></x-admin.panel><x-admin.panel heading="Customer"><div class="space-y-1"><div class="font-medium">{{ $order->customer?->name ?: 'Guest customer' }}</div><a class="text-sm text-blue-600 hover:underline" href="mailto:{{ $order->email }}">{{ $order->email }}</a></div></x-admin.panel><x-admin.panel heading="Shipping address"><address class="whitespace-pre-line text-sm not-italic">{{ collect($order->shipping_address_json)->filter()->implode("\n") ?: 'No shipping address' }}</address></x-admin.panel></div>
    </div>
    <flux:modal wire:model="showFulfillmentModal" class="md:w-[32rem]"><form wire:submit="createFulfillment" class="space-y-5"><flux:heading size="lg">Create fulfillment</flux:heading><flux:input wire:model="trackingCompany" label="Tracking company" /><flux:input wire:model="trackingNumber" label="Tracking number" />@foreach($order->lines as $line)<flux:input wire:key="fulfill-qty-{{ $line->id }}" wire:model="fulfillmentQuantities.{{ $line->id }}" type="number" min="0" max="{{ $line->quantity }}" label="{{ $line->title_snapshot }} quantity" />@endforeach<flux:error name="fulfillmentQuantities" /><div class="flex justify-end gap-2"><flux:button type="button" wire:click="$set('showFulfillmentModal', false)">Cancel</flux:button><flux:button type="submit" variant="primary">Fulfill items</flux:button></div></form></flux:modal>
    <flux:modal wire:model="showRefundModal" class="md:w-[32rem]"><form wire:submit="processRefund" class="space-y-5"><flux:heading size="lg">Process refund</flux:heading><flux:input wire:model="refundAmount" type="number" min="0.01" step="0.01" label="Amount" /><flux:textarea wire:model="refundReason" label="Reason" /><flux:checkbox wire:model="restock" label="Restock items" /><flux:error name="refundAmount" /><div class="flex justify-end gap-2"><flux:button type="button" wire:click="$set('showRefundModal', false)">Cancel</flux:button><flux:button type="submit" variant="danger">Process refund</flux:button></div></form></flux:modal>
</x-admin.page>
