<form wire:submit="save" class="mx-auto max-w-4xl space-y-6 pb-20">
    <x-admin.page-header :title="$discount ? ($discount->code ?: 'Automatic discount') : 'Create discount'" description="Configure offer value, eligibility, usage, and active dates." />
    <x-admin.card title="Discount type"><fieldset><legend class="sr-only">Discount type</legend><div class="grid gap-3 sm:grid-cols-2"><x-admin.radio name="discount-type" value="code" wire:model.live="type" :checked="$type === 'code'" label="Discount code" description="Customers enter a code at checkout." card /><x-admin.radio name="discount-type" value="automatic" wire:model.live="type" :checked="$type === 'automatic'" label="Automatic discount" description="Applied automatically when eligible." card /></div></fieldset></x-admin.card>
    @if($type === 'code')<x-admin.card title="Code"><div class="flex items-end gap-3"><div class="min-w-0 flex-1"><flux:input wire:model="code" label="Discount code" placeholder="SUMMER20" required /></div><flux:button type="button" wire:click="generateCode">Generate</flux:button></div></x-admin.card>@endif
    <x-admin.card title="Value"><fieldset><legend class="sr-only">Discount value type</legend><div class="grid gap-3 sm:grid-cols-3"><x-admin.radio name="discount-value-type" value="percent" wire:model.live="valueType" :checked="$valueType === 'percent'" label="Percentage" /><x-admin.radio name="discount-value-type" value="fixed" wire:model.live="valueType" :checked="$valueType === 'fixed'" label="Fixed amount" /><x-admin.radio name="discount-value-type" value="free_shipping" wire:model.live="valueType" :checked="$valueType === 'free_shipping'" label="Free shipping" /></div></fieldset>@if($valueType !== 'free_shipping')<div class="mt-5"><flux:input wire:model="valueAmount" type="number" min="0" :max="$valueType === 'percent' ? 100 : null" :label="$valueType === 'percent' ? 'Percentage' : 'Amount (minor units)'" required /></div>@endif</x-admin.card>
    <x-admin.card title="Conditions" description="Leave product and collection selections empty to apply store-wide.">
        <flux:input wire:model="minimumPurchaseAmount" type="number" min="0" label="Minimum purchase (minor units)" placeholder="No minimum" />
        <div class="mt-6 grid gap-6 md:grid-cols-2">
            <div class="relative"><flux:input wire:model.live.debounce.300ms="productSearch" label="Specific products" icon="magnifying-glass" placeholder="Search products…" />@if($this->productResults->isNotEmpty())<div class="absolute z-10 mt-1 w-full rounded-xl border bg-white p-2 shadow-xl dark:border-slate-700 dark:bg-slate-900">@foreach($this->productResults as $product)<button type="button" wire:click="addProduct({{ $product->id }})" class="flex w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-100 dark:hover:bg-slate-800">{{ $product->title }}</button>@endforeach</div>@endif<div class="mt-3 flex flex-wrap gap-2">@foreach($this->selectedProducts as $product)<span class="inline-flex items-center gap-1 rounded-full bg-slate-100 py-1 pl-3 pr-1 text-xs dark:bg-slate-800">{{ $product->title }}<button type="button" wire:click="removeProduct({{ $product->id }})" class="grid size-6 place-items-center rounded-full hover:bg-slate-200" aria-label="Remove {{ $product->title }}">&times;</button></span>@endforeach</div></div>
            <div class="relative"><flux:input wire:model.live.debounce.300ms="collectionSearch" label="Specific collections" icon="magnifying-glass" placeholder="Search collections…" />@if($this->collectionResults->isNotEmpty())<div class="absolute z-10 mt-1 w-full rounded-xl border bg-white p-2 shadow-xl dark:border-slate-700 dark:bg-slate-900">@foreach($this->collectionResults as $collection)<button type="button" wire:click="addCollection({{ $collection->id }})" class="flex w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-100 dark:hover:bg-slate-800">{{ $collection->title }}</button>@endforeach</div>@endif<div class="mt-3 flex flex-wrap gap-2">@foreach($this->selectedCollections as $collection)<span class="inline-flex items-center gap-1 rounded-full bg-slate-100 py-1 pl-3 pr-1 text-xs dark:bg-slate-800">{{ $collection->title }}<button type="button" wire:click="removeCollection({{ $collection->id }})" class="grid size-6 place-items-center rounded-full hover:bg-slate-200" aria-label="Remove {{ $collection->title }}">&times;</button></span>@endforeach</div></div>
        </div>
    </x-admin.card>
    <x-admin.card title="Usage limits"><div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="usageLimit" type="number" min="1" label="Total usage limit" placeholder="Unlimited" /><div class="pt-7"><flux:checkbox wire:model="onePerCustomer" label="Limit to one use per customer" /></div></div></x-admin.card>
    <x-admin.card title="Active dates"><div class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="startsAt" type="datetime-local" label="Start date" required /><flux:input wire:model="endsAt" type="datetime-local" label="End date" /></div></x-admin.card>
    <x-admin.card title="Status"><x-admin.switch wire:model="isActive" :checked="$isActive" label="Active" description="Customers can use this discount during its active dates." /></x-admin.card>
    <x-admin.sticky-save-bar :discard-url="url('/admin/discounts')" :dirty-only="false" />
</form>
