<div class="space-y-6">
    <x-admin.page-header title="Shipping" description="Configure delivery zones and rates."><x-slot:actions><flux:modal.trigger name="zone-form"><flux:button type="button" wire:click="openZoneModal" variant="primary" icon="plus">Add zone</flux:button></flux:modal.trigger></x-slot:actions></x-admin.page-header>
    <nav class="flex flex-wrap gap-1 border-b border-zinc-200"><a href="{{ url('/admin/settings') }}" wire:navigate class="px-4 py-2 text-sm text-zinc-500">General</a><a href="{{ url('/admin/settings?tab=domains') }}" wire:navigate class="px-4 py-2 text-sm text-zinc-500">Domains</a><span class="border-b-2 border-blue-600 px-4 py-2 text-sm font-medium text-blue-700">Shipping</span><a href="{{ url('/admin/settings/taxes') }}" wire:navigate class="px-4 py-2 text-sm text-zinc-500">Taxes</a><a href="{{ url('/admin/settings/checkout') }}" wire:navigate class="px-4 py-2 text-sm text-zinc-500">Checkout</a><a href="{{ url('/admin/settings/notifications') }}" wire:navigate class="px-4 py-2 text-sm text-zinc-500">Notifications</a></nav>

    <div class="space-y-5">
        @forelse($this->zones as $zone)
            <x-admin.card :title="$zone->name" :description="'Countries: '.implode(', ', (array) $zone->countries_json)">
                <x-slot:actions><flux:modal.trigger name="zone-form"><flux:button type="button" wire:click="openZoneModal({{ $zone->id }})" variant="ghost" size="sm">Edit</flux:button></flux:modal.trigger><flux:button type="button" wire:click="deleteZone({{ $zone->id }})" wire:confirm="Delete this shipping zone and all its rates?" variant="ghost" size="sm" icon="trash">Delete</flux:button></x-slot:actions>
                <x-admin.table-shell :caption="$zone->name.' rates'"><x-slot:head><tr><th>Name</th><th>Type</th><th>Price</th><th>Status</th><th class="text-right">Actions</th></tr></x-slot:head>
                    @forelse($zone->rates as $rate)@php $config=(array)$rate->config_json; $amount=(int)data_get($config,'amount',data_get($config,'ranges.0.amount',data_get($config,'fallback_amount',0))); @endphp
                        <tr wire:key="rate-{{ $rate->id }}"><td class="font-medium">{{ $rate->name }}</td><td><x-admin.status-badge :status="$rate->type" :show-dot="false" /></td><td><x-admin.money :amount="$amount" :currency="$adminStore->default_currency" /></td><td><x-admin.status-badge :status="$rate->is_active ? 'active' : 'disabled'" /></td><td><div class="flex justify-end gap-1"><flux:modal.trigger name="rate-form"><flux:button type="button" wire:click="openRateModal({{ $zone->id }}, {{ $rate->id }})" variant="ghost" size="sm">Edit</flux:button></flux:modal.trigger><flux:button type="button" wire:click="deleteRate({{ $rate->id }})" wire:confirm="Delete this rate?" variant="ghost" size="sm" icon="trash" aria-label="Delete {{ $rate->name }}" /></div></td></tr>
                    @empty<x-admin.table-empty colspan="5" title="No rates in this zone" />@endforelse
                </x-admin.table-shell>
                <div class="mt-4"><flux:modal.trigger name="rate-form"><flux:button type="button" wire:click="openRateModal({{ $zone->id }})" icon="plus" size="sm">Add rate</flux:button></flux:modal.trigger></div>
            </x-admin.card>
        @empty<x-admin.empty-state title="Add your first shipping zone" description="Group destinations and attach the rates customers can choose."><x-slot:action><flux:modal.trigger name="zone-form"><flux:button type="button" wire:click="openZoneModal" variant="primary">Add zone</flux:button></flux:modal.trigger></x-slot:action></x-admin.empty-state>@endforelse
    </div>

    <x-admin.card title="Test shipping address" description="Enter an address to see which shipping zone and rates match."><form wire:submit="testShippingAddress" class="space-y-5"><div class="grid gap-4 sm:grid-cols-2"><flux:select wire:model="testAddress.country" label="Country">@foreach($this->countries as $code => $name)<flux:select.option :value="$code">{{ $name }}</flux:select.option>@endforeach</flux:select><flux:input wire:model="testAddress.province" label="State / region" /><flux:input wire:model="testAddress.city" label="City" /><flux:input wire:model="testAddress.postal_code" label="ZIP / postal code" /></div><flux:button type="submit">Test</flux:button></form>@if($testResult)<div class="mt-5 rounded-xl bg-zinc-50 p-4 dark:bg-zinc-900">@if($testResult['zone'])<p class="font-medium">Matched zone: {{ $testResult['zone'] }}</p><ul class="mt-2 space-y-1 text-sm">@foreach($testResult['rates'] as $resultRate)<li>{{ $resultRate['name'] }} — <x-admin.money :amount="$resultRate['amount']" :currency="$adminStore->default_currency" /></li>@endforeach</ul>@else<p class="text-sm text-amber-700">No shipping zone matches this address.</p>@endif</div>@endif</x-admin.card>

    <flux:modal name="zone-form" class="max-w-lg"><form wire:submit="saveZone" class="space-y-6"><flux:heading size="lg">{{ $editingZone ? 'Edit shipping zone' : 'Add shipping zone' }}</flux:heading><flux:input wire:model="zoneName" label="Zone name" placeholder="Domestic, Europe, International…" required /><fieldset><legend class="text-sm font-medium">Countries</legend><div class="mt-3 grid max-h-64 grid-cols-2 gap-3 overflow-y-auto rounded-xl border p-4 dark:border-zinc-700">@foreach($this->countries as $code => $name)<flux:checkbox wire:model="zoneCountries" :value="$code" :label="$name" />@endforeach</div>@error('zoneCountries')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</fieldset><div class="flex justify-end gap-2"><flux:modal.close><flux:button type="button" variant="ghost">Cancel</flux:button></flux:modal.close><flux:button type="submit" variant="primary">Save zone</flux:button></div></form></flux:modal>
    <flux:modal name="rate-form" class="max-w-lg"><form wire:submit="saveRate" class="space-y-6"><flux:heading size="lg">{{ $editingRate ? 'Edit shipping rate' : 'Add shipping rate' }}</flux:heading><flux:input wire:model="rateName" label="Rate name" placeholder="Standard, Express…" required /><flux:select wire:model.live="rateType" label="Rate type"><flux:select.option value="flat">Flat rate</flux:select.option><flux:select.option value="weight">Weight-based</flux:select.option><flux:select.option value="price">Price-based</flux:select.option><flux:select.option value="carrier">Carrier-calculated</flux:select.option></flux:select>@if($rateType === 'weight')<div class="grid grid-cols-2 gap-4"><flux:input wire:model="rateConfig.min_g" type="number" min="0" label="Min weight (g)" /><flux:input wire:model="rateConfig.max_g" type="number" min="0" label="Max weight (g)" /></div>@elseif($rateType === 'price')<div class="grid grid-cols-2 gap-4"><flux:input wire:model="rateConfig.min_amount" type="number" min="0" step="0.01" label="Min order amount" /><flux:input wire:model="rateConfig.max_amount" type="number" min="0" step="0.01" label="Max order amount" /></div>@elseif($rateType === 'carrier')<p class="rounded-xl bg-blue-50 p-4 text-sm text-blue-800">Carrier-calculated rates require a carrier integration to be configured.</p>@endif @unless($rateType === 'carrier')<flux:input wire:model="rateAmount" type="number" min="0" step="0.01" label="Price" required />@endunless<x-admin.switch wire:model="rateActive" :checked="$rateActive" label="Active" /><div class="flex justify-end gap-2"><flux:modal.close><flux:button type="button" variant="ghost">Cancel</flux:button></flux:modal.close><flux:button type="submit" variant="primary">Save</flux:button></div></form></flux:modal>
</div>
