<div class="space-y-6">
    <x-admin.page-header title="Navigation" description="Choose which links appear in storefront menus." />
    <section><h2 class="mb-3 text-sm font-semibold uppercase tracking-wide text-zinc-500">Menus</h2><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach($this->menus as $menu)<button type="button" wire:click="selectMenu({{ $menu->id }})" @class(['rounded-2xl border bg-white p-5 text-left shadow-sm dark:bg-zinc-900', 'border-blue-500 ring-2 ring-blue-500/15' => $editingMenu?->id === $menu->id, 'border-zinc-200 dark:border-zinc-800' => $editingMenu?->id !== $menu->id])><span class="font-semibold text-zinc-950 dark:text-white">{{ $menu->title }}</span><span class="mt-1 block text-sm text-zinc-500">{{ $menu->items_count }} {{ Str::plural('item', $menu->items_count) }}</span></button>@endforeach</div></section>
    @if($editingMenu)<x-admin.card :title="$editingMenu->title" description="Drag-and-drop support can call reorderItems; changes are stored when you save."><x-slot:actions><flux:modal.trigger name="item-form"><flux:button type="button" wire:click="addItem" icon="plus">Add item</flux:button></flux:modal.trigger></x-slot:actions>
        <div class="space-y-2">@forelse($menuItems as $index => $item)<div wire:key="menu-item-{{ $index }}" class="flex items-center gap-3 rounded-xl border border-zinc-200 p-3 dark:border-zinc-800"><flux:icon.bars-3 class="size-5 text-zinc-400" /><div class="min-w-0 flex-1"><p class="font-medium">{{ $item['label'] }}</p><p class="truncate text-xs text-zinc-500">{{ $item['type'] }}: {{ $item['url'] ?: ($item['resource_id'] ?? '—') }}</p></div><flux:modal.trigger name="item-form"><flux:button type="button" wire:click="editItem({{ $index }})" variant="ghost" size="sm" icon="pencil" aria-label="Edit {{ $item['label'] }}" /></flux:modal.trigger><flux:button type="button" wire:click="removeItem({{ $index }})" variant="ghost" size="sm" icon="trash" aria-label="Remove {{ $item['label'] }}" /></div>@empty<p class="rounded-xl border border-dashed p-6 text-center text-sm text-zinc-500">This menu has no items.</p>@endforelse</div>
        <div class="mt-5 flex justify-end"><flux:button type="button" wire:click="saveMenu" variant="primary">Save menu</flux:button></div>
    </x-admin.card>@else<x-admin.empty-state title="No navigation menus" description="Seed or create a navigation menu to begin." />@endif
    <flux:modal name="item-form" class="max-w-md"><form wire:submit="saveItem" class="space-y-6"><flux:heading size="lg">{{ $editingItemIndex === null ? 'Add menu item' : 'Edit menu item' }}</flux:heading><flux:input wire:model="itemLabel" label="Label" placeholder="About Us" required /><flux:select wire:model.live="itemType" label="Type"><flux:select.option value="link">Custom link</flux:select.option><flux:select.option value="page">Page</flux:select.option><flux:select.option value="collection">Collection</flux:select.option><flux:select.option value="product">Product</flux:select.option></flux:select>@if($itemType === 'link')<flux:input wire:model="itemUrl" label="URL" placeholder="/pages/about" required />@else<flux:select wire:model="itemResourceId" label="Resource" placeholder="Select a resource">@foreach(($this->resources[$itemType] ?? []) as $resource)<flux:select.option :value="$resource['id']">{{ $resource['label'] }}</flux:select.option>@endforeach</flux:select>@endif<div class="flex justify-end gap-2"><flux:modal.close><flux:button type="button" variant="ghost">Cancel</flux:button></flux:modal.close><flux:button type="submit" variant="primary">Save item</flux:button></div></form></flux:modal>
</div>
