<div class="space-y-6">
    <x-admin.page-header title="Inventory" description="Review stock levels and update availability by variant." />
    <x-admin.list-toolbar><x-slot:search><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="Search by product or SKU…" aria-label="Search inventory" /></x-slot:search><x-slot:filters><flux:select wire:model.live="stockFilter" aria-label="Filter stock"><flux:select.option value="all">All stock</flux:select.option><flux:select.option value="in_stock">In stock</flux:select.option><flux:select.option value="low_stock">Low stock</flux:select.option><flux:select.option value="out_of_stock">Out of stock</flux:select.option></flux:select></x-slot:filters></x-admin.list-toolbar>
    <x-admin.table-shell caption="Inventory by variant" loading-target="search,stockFilter">
        <x-slot:head><tr><th>Product</th><th>Variant</th><th>SKU</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Policy</th></tr></x-slot:head>
        @forelse($this->inventoryItems as $item)
            @php $variantName = $item->variant->optionValues->sortBy(fn($value) => $value->option?->position)->pluck('value')->implode(' / ') ?: 'Default'; $available = $item->availableQuantity(); @endphp
            <tr wire:key="inventory-{{ $item->id }}"><td><a href="{{ url('/admin/products/'.$item->variant->product_id.'/edit') }}" wire:navigate class="font-medium hover:text-blue-700">{{ $item->variant->product->title }}</a></td><td>{{ $variantName }}</td><td class="font-mono text-xs">{{ $item->variant->sku ?: '—' }}</td><td><input type="number" min="0" value="{{ $item->quantity_on_hand }}" wire:change="updateQuantity({{ $item->id }}, $event.target.value)" class="admin-input w-24" aria-label="On hand quantity for {{ $item->variant->product->title }} {{ $variantName }}" @disabled($adminRole === 'support')></td><td class="tabular-nums">{{ $item->quantity_reserved }}</td><td><x-admin.status-badge :status="$available <= 0 ? 'out_of_stock' : ($available <= 10 ? 'low_stock' : 'in_stock')" :label="(string) $available" /></td><td><select wire:change="updatePolicy({{ $item->id }}, $event.target.value)" class="admin-input min-w-28" aria-label="Inventory policy" @disabled($adminRole === 'support')><option value="deny" @selected(($item->policy->value ?? $item->policy) === 'deny')>Stop selling</option><option value="continue" @selected(($item->policy->value ?? $item->policy) === 'continue')>Continue</option></select></td></tr>
        @empty<x-admin.table-empty colspan="7" title="No inventory items found" description="Inventory appears after a product variant is created." />@endforelse
        <x-slot:pagination>{{ $this->inventoryItems->links() }}</x-slot:pagination>
    </x-admin.table-shell>
</div>
