<div class="space-y-8">
    <div><p class="text-sm font-semibold uppercase tracking-widest text-blue-600">Configuration</p><flux:heading size="xl" level="1" class="mt-2">Store settings</flux:heading><flux:text class="mt-2" variant="subtle">Manage store details and defaults used throughout the storefront.</flux:text></div>
    @if ($message)<div role="status" class="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ $message }}</div>@endif
    <form wire:submit="save" class="space-y-8">
        <section class="grid gap-6 border-b border-zinc-200 pb-8 lg:grid-cols-[220px_1fr]"><div><flux:heading size="lg">Store details</flux:heading><flux:text class="mt-2" variant="subtle">Basic information about your store.</flux:text></div><div class="space-y-5 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><flux:input wire:model="storeName" label="Store name" required /><flux:input wire:model="storeHandle" label="Store handle" disabled description="The store handle cannot be changed after creation." /></div></section>
        <section class="grid gap-6 border-b border-zinc-200 pb-8 lg:grid-cols-[220px_1fr]"><div><flux:heading size="lg">Defaults</flux:heading><flux:text class="mt-2" variant="subtle">Currency, language, and timezone settings.</flux:text></div><div class="grid gap-5 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200 sm:grid-cols-2"><flux:select wire:model="defaultCurrency" label="Default currency">@foreach ($currencies as $code => $label)<option value="{{ $code }}">{{ $label }}</option>@endforeach</flux:select><flux:select wire:model="defaultLocale" label="Default locale">@foreach ($locales as $code => $label)<option value="{{ $code }}">{{ $label }}</option>@endforeach</flux:select><flux:select wire:model="timezone" label="Timezone" class="sm:col-span-2">@foreach ($timezones as $timezoneOption)<option value="{{ $timezoneOption }}">{{ $timezoneOption }}</option>@endforeach</flux:select></div></section>
        <div class="flex justify-end"><flux:button type="submit" variant="primary">Save settings</flux:button></div>
    </form>
    <section class="space-y-5"><div><flux:heading size="lg">Domains</flux:heading><flux:text class="mt-2" variant="subtle">Manage the hostnames that point to this store.</flux:text></div><livewire:admin.settings.domains /></section>
    <nav class="flex flex-wrap gap-3" aria-label="More settings"><flux:button variant="ghost" :href="route('admin.settings.shipping')" wire:navigate>Shipping</flux:button><flux:button variant="ghost" :href="route('admin.settings.taxes')" wire:navigate>Taxes</flux:button></nav>
</div>
