<div class="mx-auto max-w-3xl space-y-6">
    <div><a href="{{ route('admin.settings') }}" wire:navigate class="text-sm text-blue-700 hover:underline">← Settings</a><flux:heading size="xl" level="1" class="mt-3">Taxes</flux:heading><flux:text class="mt-2" variant="subtle">Choose manual rates or configure a tax provider.</flux:text></div>
    @if ($message)<div role="status" class="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ $message }}</div>@endif
    <form wire:submit="save" class="space-y-6">
        <section class="space-y-4 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><flux:heading size="lg">Mode selection</flux:heading><label class="flex cursor-pointer gap-3 rounded-xl border p-4 has-[:checked]:border-blue-600"><input type="radio" wire:model.live="mode" value="manual" class="mt-1 text-blue-600"><span><span class="block font-medium">Manual tax rates</span><span class="block text-sm text-zinc-500">Define tax rates per zone manually.</span></span></label><label class="flex cursor-pointer gap-3 rounded-xl border p-4 has-[:checked]:border-blue-600"><input type="radio" wire:model.live="mode" value="provider" class="mt-1 text-blue-600"><span><span class="block font-medium">Tax provider</span><span class="block text-sm text-zinc-500">Use an automated tax calculation service.</span></span></label></section>
        @if ($mode === 'manual')<section class="space-y-4 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><div class="flex items-center justify-between gap-3"><flux:heading size="lg">Manual rates</flux:heading><flux:button type="button" size="sm" wire:click="addManualRate">Add rate</flux:button></div><div class="space-y-3">@foreach ($manualRates as $index => $manualRate)<div wire:key="manual-rate-{{ $index }}" class="grid items-end gap-3 sm:grid-cols-[1fr_160px_auto]"><flux:input wire:model="manualRates.{{ $index }}.zone_name" label="{{ $index === 0 ? 'Zone name' : '' }}" placeholder="EU or DE" /><flux:input wire:model="manualRates.{{ $index }}.rate_percentage" label="{{ $index === 0 ? 'Rate (%)' : '' }}" type="number" min="0" max="100" step="0.01" placeholder="19.00" /><flux:button type="button" variant="ghost" wire:click="removeManualRate({{ $index }})" aria-label="Remove rate">Remove</flux:button></div>@endforeach</div></section>@else<section class="space-y-4 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><flux:heading size="lg">Provider configuration</flux:heading><flux:select wire:model="provider" label="Provider"><option value="none">None</option><option value="stripe_tax">Stripe Tax</option></flux:select>@if ($providerKeyConfigured)<p class="text-sm text-zinc-500">An API key is configured. Leave the field blank to keep it.</p>@endif<flux:input wire:model="providerApiKey" label="API key" type="password" placeholder="Leave blank to keep the current key" /></section>@endif
        <section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-zinc-200"><label class="flex items-center gap-3"><input type="checkbox" wire:model="pricesIncludeTax" class="rounded border-zinc-300 text-blue-600"><span class="font-medium">Prices include tax</span></label><p class="mt-2 text-sm text-zinc-500">When enabled, listed prices include tax and tax is calculated backwards from the price.</p></section>
        <div class="flex justify-end"><flux:button type="submit" variant="primary">Save tax settings</flux:button></div>
    </form>
</div>
