<div class="space-y-6">
    <x-admin.page-header :title="$customer->name ?: 'Guest customer'" :description="$customer->email"><x-slot:actions><x-admin.status-badge :status="$customer->marketing_opt_in ? 'active' : 'disabled'" :label="$customer->marketing_opt_in ? 'Marketing opted in' : 'Marketing opted out'" /></x-slot:actions></x-admin.page-header>
    <div class="grid items-start gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(19rem,1fr)]">
        <div class="space-y-6">
            <x-admin.card title="Customer information"><dl class="grid gap-5 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Name</dt><dd class="mt-1 font-medium">{{ $customer->name ?: 'Not provided' }}</dd></div><div><dt class="text-slate-500">Email</dt><dd class="mt-1 font-medium">{{ $customer->email }}</dd></div><div><dt class="text-slate-500">Created</dt><dd class="mt-1">{{ $customer->created_at->format('M j, Y g:i A') }}</dd></div><div><dt class="text-slate-500">Account</dt><dd class="mt-1">{{ $customer->password_hash ? 'Registered' : 'Guest checkout' }}</dd></div></dl></x-admin.card>
            <x-admin.card title="Order history">
                <div class="overflow-x-auto"><table class="admin-table"><thead><tr><th>Order</th><th>Date</th><th>Payment</th><th class="text-right">Total</th></tr></thead><tbody>@forelse($this->orders as $order)<tr><td><a href="{{ url('/admin/orders/'.$order->id) }}" wire:navigate class="font-semibold text-blue-700 hover:underline dark:text-blue-300">{{ $order->order_number }}</a></td><td>{{ ($order->placed_at ?? $order->created_at)->format('M j, Y') }}</td><td><x-admin.status-badge :status="$order->financial_status" /></td><td class="text-right"><x-admin.money :amount="$order->total_amount" :currency="$order->currency" /></td></tr>@empty<tr><td colspan="4" class="py-10 text-center text-sm text-slate-500">This customer has no orders yet.</td></tr>@endforelse</tbody></table></div>
                <div class="mt-4">{{ $this->orders->links() }}</div>
            </x-admin.card>
        </div>
        <x-admin.card title="Addresses" class="xl:sticky xl:top-24">
            <x-slot:actions>@if($adminRole !== 'support')<flux:modal.trigger name="address-form"><flux:button type="button" wire:click="openAddressForm" size="sm" icon="plus">Add</flux:button></flux:modal.trigger>@endif</x-slot:actions>
            <div class="space-y-4">@forelse($customer->addresses as $address)@php $a = (array)$address->address_json; @endphp<div class="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div class="flex items-start justify-between gap-3"><div><p class="font-medium">{{ $address->label ?: 'Address' }}</p>@if($address->is_default)<x-admin.status-badge status="active" label="Default" class="mt-2" />@endif</div>@if($adminRole !== 'support')<div class="flex"><flux:modal.trigger name="address-form"><flux:button type="button" wire:click="openAddressForm({{ $address->id }})" variant="ghost" size="sm" icon="pencil" aria-label="Edit address" /></flux:modal.trigger><flux:button type="button" wire:click="deleteAddress({{ $address->id }})" wire:confirm="Delete this address?" variant="ghost" size="sm" icon="trash" aria-label="Delete address" /></div>@endif</div><address class="mt-3 space-y-0.5 text-sm not-italic text-slate-500"><p>{{ trim(($a['first_name'] ?? '').' '.($a['last_name'] ?? '')) }}</p><p>{{ $a['address1'] ?? '' }}</p>@if($a['address2'] ?? null)<p>{{ $a['address2'] }}</p>@endif<p>{{ $a['zip'] ?? '' }} {{ $a['city'] ?? '' }}</p><p>{{ $a['country'] ?? $a['country_code'] ?? '' }}</p></address>@if(!$address->is_default && $adminRole !== 'support')<flux:button type="button" wire:click="setDefaultAddress({{ $address->id }})" variant="ghost" size="sm" class="mt-2">Set as default</flux:button>@endif</div>@empty<p class="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500 dark:border-slate-700">No saved addresses.</p>@endforelse</div>
        </x-admin.card>
    </div>

    <flux:modal name="address-form" class="max-w-2xl"><form wire:submit="saveAddress" class="space-y-6"><div><flux:heading size="lg">{{ $editingAddress ? 'Edit address' : 'Add address' }}</flux:heading><flux:text class="mt-2">Keep delivery details accurate for customer support.</flux:text></div><div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="addressLabel" label="Label" placeholder="Home, Office…" /><flux:input wire:model="addressJson.company" label="Company" /><flux:input wire:model="addressJson.first_name" label="First name" required /><flux:input wire:model="addressJson.last_name" label="Last name" required /><div class="sm:col-span-2"><flux:input wire:model="addressJson.address1" label="Address line 1" required /></div><div class="sm:col-span-2"><flux:input wire:model="addressJson.address2" label="Address line 2" /></div><flux:input wire:model="addressJson.city" label="City" required /><flux:input wire:model="addressJson.province" label="State / province" /><flux:input wire:model="addressJson.zip" label="ZIP / postal code" required /><flux:input wire:model="addressJson.country" label="Country" required /><flux:input wire:model="addressJson.country_code" label="Country code" maxlength="2" placeholder="DE" required /><flux:input wire:model="addressJson.phone" label="Phone" type="tel" /></div><flux:checkbox wire:model="addressIsDefault" label="Make this the default address" /><div class="flex justify-end gap-2"><flux:modal.close><flux:button type="button" variant="ghost">Cancel</flux:button></flux:modal.close><flux:button type="submit" variant="primary" wire:loading.attr="disabled">Save address</flux:button></div></form></flux:modal>
</div>
