<div class="-m-4 flex min-h-[calc(100vh-4rem)] flex-col sm:-m-6 lg:-m-8" x-data="{ previewSrc: @js($previewUrl) }" x-on:theme-preview-refresh.window="previewSrc = $event.detail.url + '&refresh=' + Date.now()">
    <header class="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-200 bg-white px-5 py-3 dark:border-zinc-800 dark:bg-zinc-950"><flux:button type="button" wire:click="leaveEditor" variant="ghost" icon="arrow-left">Back to themes</flux:button><div class="flex items-center gap-2"><x-admin.status-badge :status="$theme->status" /><flux:button type="button" wire:click="save">Save</flux:button><flux:button type="button" wire:click="publish" variant="primary">Save and publish</flux:button></div></header>
    <div class="grid min-h-0 flex-1 lg:grid-cols-[264px_minmax(360px,1fr)_320px]">
        <aside class="border-r border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950"><h2 class="px-3 text-sm font-semibold uppercase tracking-wide text-zinc-500">Sections</h2><nav class="mt-3 space-y-1">@foreach($sections as $key => $section)<button type="button" wire:click="selectSection('{{ $key }}')" @class(['w-full rounded-xl px-3 py-2 text-left text-sm', 'bg-blue-50 font-semibold text-blue-700 dark:bg-blue-950' => $selectedSection === $key, 'text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-900' => $selectedSection !== $key])>{{ $section['label'] }}</button>@endforeach</nav></aside>
        <main class="min-h-[36rem] bg-zinc-100 p-5 dark:bg-zinc-900"><div class="h-full overflow-hidden rounded-2xl border border-zinc-300 bg-white shadow-sm dark:border-zinc-700"><iframe x-bind:src="previewSrc" title="Storefront theme preview" class="h-full min-h-[36rem] w-full"></iframe></div></main>
        <aside class="border-l border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950">
            @if($selectedSection)<h2 class="text-lg font-semibold">{{ $sections[$selectedSection]['label'] }}</h2><div class="mt-5 space-y-5">@foreach($sections[$selectedSection]['fields'] as $key => $field)@php $value=data_get($allSettings,$key,$field['default'] ?? null); @endphp
                @if($field['type'] === 'checkbox')<x-admin.switch :checked="(bool)$value" :label="$field['label']" wire:change="updateSetting('{{ $key }}', $event.target.checked)" />
                @elseif($field['type'] === 'textarea')<flux:textarea :value="$value" :label="$field['label']" rows="3" wire:change="updateSetting('{{ $key }}', $event.target.value)" />
                @elseif($field['type'] === 'select')<flux:select :label="$field['label']" wire:change="updateSetting('{{ $key }}', $event.target.value)">@foreach($field['options'] as $optionValue => $optionLabel)<flux:select.option :value="$optionValue" :selected="$value === $optionValue">{{ $optionLabel }}</flux:select.option>@endforeach</flux:select>
                @elseif($field['type'] === 'color')<label class="block text-sm font-medium text-zinc-700 dark:text-zinc-200">{{ $field['label'] }}<span class="mt-2 flex items-center gap-3"><input type="color" value="{{ $value }}" wire:change="updateSetting('{{ $key }}', $event.target.value)" class="h-10 w-16 rounded border"><span class="font-mono text-xs">{{ $value }}</span></span></label>
                @else<flux:input :value="$value" :label="$field['label']" wire:change="updateSetting('{{ $key }}', $event.target.value)" />@endif
            @endforeach</div>@else<div class="grid h-full place-items-center text-center text-sm text-zinc-500">Select a section to edit its settings.</div>@endif
        </aside>
    </div>
</div>
