<x-admin.page :title="$this->isEditing ? $title : 'Add product'" subtitle="Product details, pricing, inventory, and organization.">
    <x-slot:actions>@if($this->isEditing)<flux:button wire:click="archive" variant="danger" icon="archive-box">Archive</flux:button>@endif<flux:button wire:click="save" variant="primary" icon="check" wire:loading.attr="disabled">Save product</flux:button></x-slot:actions>
    <form wire:submit="save" class="grid gap-6 xl:grid-cols-3">
        <div class="space-y-6 xl:col-span-2">
            <x-admin.panel heading="Product information"><div class="space-y-5"><flux:field><flux:label>Title</flux:label><flux:input wire:model.live="title" placeholder="Short Sleeve T-Shirt" /><flux:error name="title" /></flux:field><flux:field><flux:label>Description</flux:label><flux:textarea wire:model="descriptionHtml" rows="8" placeholder="Describe your product…" /><flux:error name="descriptionHtml" /></flux:field><flux:field><flux:label>URL handle</flux:label><flux:input wire:model="handle" prefix="/products/" /><flux:error name="handle" /></flux:field></div></x-admin.panel>
            <x-admin.panel heading="Variants" description="Add prices, SKUs, and inventory for each sellable variant."><div class="space-y-4">@foreach($variants as $index => $variant)<div wire:key="variant-{{ $index }}" class="grid gap-3 rounded-xl border border-zinc-200 p-4 dark:border-zinc-800 sm:grid-cols-2 lg:grid-cols-5"><flux:input wire:model="variants.{{ $index }}.sku" label="SKU" /><flux:input wire:model="variants.{{ $index }}.price" type="number" min="0" label="Price (cents)" /><flux:input wire:model="variants.{{ $index }}.compareAtPrice" type="number" min="0" label="Compare at" /><flux:input wire:model="variants.{{ $index }}.quantity" type="number" min="0" label="Quantity" /><div class="flex items-end justify-between gap-2 pb-2"><flux:checkbox wire:model="variants.{{ $index }}.requiresShipping" label="Ships" /><flux:button type="button" wire:click="removeVariant({{ $index }})" variant="ghost" icon="trash" aria-label="Remove variant" /></div></div>@endforeach<flux:button type="button" wire:click="addVariant" variant="ghost" icon="plus">Add variant</flux:button><flux:error name="variants" /></div></x-admin.panel>
        </div>
        <div class="space-y-6">
            <x-admin.panel heading="Publishing"><div class="space-y-4"><flux:select wire:model="status" label="Status"><flux:select.option value="draft">Draft</flux:select.option><flux:select.option value="active">Active</flux:select.option><flux:select.option value="archived">Archived</flux:select.option></flux:select><flux:input wire:model="publishedAt" type="datetime-local" label="Published at" /></div></x-admin.panel>
            <x-admin.panel heading="Organization"><div class="space-y-4"><flux:input wire:model="vendor" label="Vendor" /><flux:input wire:model="productType" label="Product type" /><flux:input wire:model="tags" label="Tags" description="Separate tags with commas." /></div></x-admin.panel>
            <x-admin.panel heading="Collections"><div class="grid gap-3">@forelse($this->availableCollections as $collection)<flux:checkbox wire:key="collection-choice-{{ $collection->id }}" wire:model="collectionIds" value="{{ $collection->id }}" label="{{ $collection->title }}" />@empty<flux:text>No collections yet.</flux:text>@endforelse</div></x-admin.panel>
        </div>
        <div class="sticky bottom-0 z-20 flex justify-end gap-2 border-t border-zinc-200 bg-white/95 p-4 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/95 xl:col-span-3"><flux:button href="/admin/products" wire:navigate>Discard</flux:button><flux:button type="submit" variant="primary" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Save</span><span wire:loading wire:target="save">Saving…</span></flux:button></div>
    </form>
</x-admin.page>
