<div class="sf-container sf-page-y max-w-4xl">
    <header class="text-center"><div class="mx-auto grid size-16 place-items-center rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"><svg aria-hidden="true" class="size-8" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.704 4.153a.75.75 0 0 1 .143 1.051l-8 10.5a.75.75 0 0 1-1.127.075l-4.5-4.5a.75.75 0 0 1 1.06-1.06l3.894 3.893 7.48-9.817a.75.75 0 0 1 1.05-.142Z" clip-rule="evenodd"/></svg></div><p class="sf-eyebrow mt-6">Order {{ $order->order_number }}</p><h1 class="sf-page-title mt-2">Thank you for your order!</h1><p class="mx-auto mt-4 max-w-xl text-slate-600 dark:text-slate-300">We’ve sent a confirmation to {{ $order->email }}. We’ll let you know when your order is on its way.</p></header>

    @if (($order->payment_method instanceof \BackedEnum ? $order->payment_method->value : $order->payment_method) === 'bank_transfer')
        <section class="sf-callout sf-callout-info mt-10 p-6" aria-labelledby="bank-transfer-heading"><h2 id="bank-transfer-heading" class="text-lg font-semibold">Bank Transfer Instructions</h2><p class="mt-3">Please transfer the total amount to the following account:</p><dl class="mt-4 grid grid-cols-[auto_1fr] gap-x-5 gap-y-2 text-sm"><dt class="text-slate-500">Bank</dt><dd class="font-medium">Mock Bank AG</dd><dt class="text-slate-500">IBAN</dt><dd class="font-mono font-medium">DE89 3704 0044 0532 0130 00</dd><dt class="text-slate-500">BIC</dt><dd class="font-mono font-medium">COBADEFFXXX</dd><dt class="text-slate-500">Amount</dt><dd class="font-medium"><x-storefront.price :amount="$order->total_amount" :currency="$order->currency" /></dd><dt class="text-slate-500">Reference</dt><dd class="font-medium">{{ $order->order_number }}</dd></dl><p class="mt-4 text-sm">Please complete your transfer within 7 days. Your order will be processed once payment is confirmed.</p></section>
    @endif

    <section class="sf-card mt-10" aria-labelledby="confirmation-summary-heading"><h2 id="confirmation-summary-heading" class="text-xl font-semibold">Order Summary</h2><div class="mt-5 divide-y divide-slate-200 dark:divide-slate-800">@foreach($order->lines as $line)<div class="flex items-center gap-4 py-4"><div class="size-14 rounded-xl bg-slate-100 dark:bg-slate-800">@php($media = optional(optional($line->product)->media->first())->storage_key)@if($media)<img src="{{ Storage::disk('public')->url($media) }}" alt="" class="h-full w-full rounded-xl object-cover">@endif</div><div class="min-w-0 flex-1"><p class="font-medium">{{ $line->title_snapshot }}</p><p class="mt-1 text-sm text-slate-500">Quantity: {{ $line->quantity }}</p></div><strong><x-storefront.price :amount="$line->total_amount" :currency="$order->currency" /></strong></div>@endforeach</div></section>

    @php($shippingAddress = is_string($order->shipping_address_json) ? json_decode($order->shipping_address_json, true) : (array) $order->shipping_address_json)
    <div class="mt-6 grid gap-6 md:grid-cols-2"><section class="sf-card"><h2 class="font-semibold">Shipping Address</h2><address class="mt-3 text-sm not-italic leading-6 text-slate-600 dark:text-slate-300">{{ data_get($shippingAddress, 'first_name') }} {{ data_get($shippingAddress, 'last_name') }}<br>{{ data_get($shippingAddress, 'address1') }}<br>{{ data_get($shippingAddress, 'zip', data_get($shippingAddress, 'postal_code')) }} {{ data_get($shippingAddress, 'city') }}<br>{{ data_get($shippingAddress, 'country_code', data_get($shippingAddress, 'country')) }}</address></section><section class="sf-card"><h2 class="font-semibold">Payment Method</h2><p class="mt-3 text-sm capitalize text-slate-600 dark:text-slate-300">{{ str_replace('_', ' ', $order->payment_method instanceof \BackedEnum ? $order->payment_method->value : $order->payment_method) }}</p></section></div>

    <dl class="ml-auto mt-8 max-w-sm space-y-3 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd><x-storefront.price :amount="$order->subtotal_amount" :currency="$order->currency" /></dd></div>@if($order->discount_amount > 0)<div class="flex justify-between text-emerald-700"><dt>Discount</dt><dd>-<x-storefront.price :amount="$order->discount_amount" :currency="$order->currency" /></dd></div>@endif<div class="flex justify-between"><dt>Shipping</dt><dd><x-storefront.price :amount="$order->shipping_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between"><dt>Tax</dt><dd><x-storefront.price :amount="$order->tax_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between border-t border-slate-200 pt-4 text-lg font-semibold dark:border-slate-800"><dt>Total</dt><dd><x-storefront.price :amount="$order->total_amount" :currency="$order->currency" /></dd></div></dl>

    <div class="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><a href="{{ url('/') }}" wire:navigate class="sf-button sf-button-primary">Continue shopping</a>@auth('customer')<a href="{{ url('/account/orders/'.$order->order_number) }}" wire:navigate class="sf-button sf-button-secondary">View order</a>@endauth</div>
</div>
