<div class="space-y-6">
    <x-admin.page-header title="Orders" description="Track payment, fulfillment, refunds, and customer delivery." />
    <flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="Search by order number, email, or customer…" aria-label="Search orders" class="max-w-lg" />
    <div class="overflow-x-auto border-b border-slate-200 dark:border-slate-800" role="tablist" aria-label="Order status filters">@foreach(['all','pending','paid','fulfilled','cancelled','refunded'] as $status)<button type="button" wire:click="setStatus('{{ $status }}')" role="tab" aria-selected="{{ $statusFilter === $status ? 'true' : 'false' }}" class="-mb-px min-h-11 whitespace-nowrap border-b-2 px-4 text-sm font-medium {{ $statusFilter === $status ? 'border-blue-600 text-blue-700 dark:text-blue-300' : 'border-transparent text-slate-500 hover:text-slate-900 dark:hover:text-white' }}">{{ Str::headline($status) }}</button>@endforeach</div>
    <x-admin.table-shell caption="Orders" loading-target="search,statusFilter,setStatus">
        <x-slot:head><tr><th><button wire:click="sortBy('order_number')">Order</button></th><th><button wire:click="sortBy('placed_at')">Date</button></th><th>Customer</th><th>Payment</th><th>Fulfillment</th><th class="text-right"><button wire:click="sortBy('total_amount')">Total</button></th></tr></x-slot:head>
        @forelse($this->orders as $order)<tr wire:key="order-{{ $order->id }}"><td><a href="{{ url('/admin/orders/'.$order->id) }}" wire:navigate class="font-semibold text-blue-700 hover:underline dark:text-blue-300">{{ $order->order_number }}</a></td><td class="whitespace-nowrap">{{ $order->placed_at?->format('M j, Y g:i A') ?: $order->created_at->format('M j, Y g:i A') }}</td><td><p class="font-medium">{{ $order->customer?->name ?: 'Guest' }}</p><p class="text-xs text-slate-500">{{ $order->email }}</p></td><td><x-admin.status-badge :status="$order->financial_status" /></td><td><x-admin.status-badge :status="$order->fulfillment_status" /></td><td class="text-right font-medium"><x-admin.money :amount="$order->total_amount" :currency="$order->currency" /></td></tr>
        @empty<x-admin.table-empty colspan="6" title="No orders found" description="Orders will appear here after checkout." />@endforelse
        <x-slot:pagination>{{ $this->orders->links() }}</x-slot:pagination>
    </x-admin.table-shell>
</div>
