@php
    $financial = $order->financial_status->value ?? $order->financial_status;
    $fulfillmentStatus = $order->fulfillment_status->value ?? $order->fulfillment_status;
    $paymentMethod = $order->payment_method->value ?? $order->payment_method;
    $addressLines = fn($address) => array_filter([trim(($address['first_name'] ?? '').' '.($address['last_name'] ?? '')), $address['line1'] ?? $address['address_line_1'] ?? null, $address['line2'] ?? $address['address_line_2'] ?? null, trim(($address['postal_code'] ?? '').' '.($address['city'] ?? '')), $address['province'] ?? $address['state'] ?? null, $address['country'] ?? $address['country_code'] ?? null]);
@endphp
<div class="space-y-6">
    <x-admin.page-header :title="$order->order_number" :description="'Placed '.($order->placed_at?->format('M j, Y \a\t g:i A') ?? $order->created_at->format('M j, Y \a\t g:i A'))">
        <x-slot:actions><x-admin.status-badge :status="$order->financial_status" /><x-admin.status-badge :status="$order->fulfillment_status" /></x-slot:actions>
    </x-admin.page-header>

    <div class="flex flex-wrap gap-2">
        @if($paymentMethod === 'bank_transfer' && $financial === 'pending' && $adminRole !== 'support')<flux:button wire:click="confirmPayment" variant="primary" wire:confirm="Confirm that this bank transfer has been received?">Confirm payment</flux:button>@endif
        @if(in_array($financial, ['paid','partially_refunded']) && $fulfillmentStatus !== 'fulfilled' && $adminRole !== 'support')<flux:modal.trigger name="create-fulfillment"><flux:button type="button" wire:click="openFulfillmentModal" icon="truck">Create fulfillment</flux:button></flux:modal.trigger>@endif
        @if(in_array($financial, ['paid','partially_refunded']) && in_array($adminRole, ['owner','admin']))<flux:modal.trigger name="create-refund"><flux:button type="button" wire:click="openRefundModal" variant="danger" icon="arrow-uturn-left">Refund</flux:button></flux:modal.trigger>@endif
    </div>
    @if(!in_array($financial, ['paid','partially_refunded']))<flux:callout variant="warning" icon="exclamation-triangle" heading="Cannot create fulfillment">Payment must be confirmed before items can be fulfilled. Current financial status: {{ Str::headline($financial) }}.</flux:callout>@endif

    <div class="grid items-start gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(19rem,1fr)]">
        <div class="space-y-6">
            <x-admin.card title="Order lines">
                <div class="overflow-x-auto"><table class="admin-table"><thead><tr><th>Product</th><th>SKU</th><th>Qty</th><th class="text-right">Unit price</th><th class="text-right">Total</th></tr></thead><tbody>@foreach($order->lines as $line)<tr><td class="font-medium">{{ $line->title_snapshot }}</td><td class="font-mono text-xs">{{ $line->sku_snapshot ?: '—' }}</td><td>{{ $line->quantity }}</td><td class="text-right"><x-admin.money :amount="$line->unit_price_amount" :currency="$order->currency" /></td><td class="text-right"><x-admin.money :amount="$line->total_amount" :currency="$order->currency" /></td></tr>@endforeach</tbody></table></div>
                <dl class="ml-auto mt-5 max-w-sm space-y-2 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd><x-admin.money :amount="$order->subtotal_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between"><dt>Discount</dt><dd>-<x-admin.money :amount="$order->discount_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between"><dt>Shipping</dt><dd><x-admin.money :amount="$order->shipping_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between"><dt>Tax</dt><dd><x-admin.money :amount="$order->tax_amount" :currency="$order->currency" /></dd></div><div class="flex justify-between border-t border-slate-200 pt-3 text-base font-semibold dark:border-slate-700"><dt>Total</dt><dd><x-admin.money :amount="$order->total_amount" :currency="$order->currency" /></dd></div></dl>
            </x-admin.card>

            <x-admin.card title="Payment details"><div class="space-y-4">@forelse($order->payments as $payment)<div class="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-700"><div><p class="font-medium">{{ Str::headline($payment->method->value ?? $payment->method) }}</p><p class="mt-1 text-xs text-slate-500">{{ $payment->provider_payment_id ?: 'No provider reference' }}</p></div><div class="flex items-center gap-3"><x-admin.status-badge :status="$payment->status" /><x-admin.money :amount="$payment->amount" :currency="$payment->currency" /></div></div>@empty<p class="text-sm text-slate-500">No payment records.</p>@endforelse</div></x-admin.card>

            <x-admin.card title="Fulfillments">
                <div class="space-y-4">@forelse($order->fulfillments as $fulfillment)<div class="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div class="flex flex-wrap items-center justify-between gap-3"><x-admin.status-badge :status="$fulfillment->status" /><div class="flex gap-2">@if(($fulfillment->status->value ?? $fulfillment->status) === 'pending' && $adminRole !== 'support')<flux:button size="sm" wire:click="markAsShipped({{ $fulfillment->id }})">Mark shipped</flux:button>@elseif(($fulfillment->status->value ?? $fulfillment->status) === 'shipped' && $adminRole !== 'support')<flux:button size="sm" variant="primary" wire:click="markAsDelivered({{ $fulfillment->id }})">Mark delivered</flux:button>@endif</div></div><p class="mt-3 text-sm text-slate-500">{{ $fulfillment->tracking_company ?: 'No carrier' }} · {{ $fulfillment->tracking_number ?: 'No tracking number' }}</p>@if($fulfillment->tracking_url)<a href="{{ $fulfillment->tracking_url }}" target="_blank" rel="noopener" class="mt-1 inline-flex text-sm text-blue-700 hover:underline">Track shipment</a>@endif<ul class="mt-3 space-y-1 text-sm">@foreach($fulfillment->lines as $line)<li>{{ $line->quantity }} × {{ $line->orderLine?->title_snapshot }}</li>@endforeach</ul></div>@empty<p class="text-sm text-slate-500">No fulfillments created yet.</p>@endforelse</div>
            </x-admin.card>

            <x-admin.card title="Activity timeline"><ol class="space-y-5 border-l border-slate-200 pl-5 dark:border-slate-700"><li class="relative"><span class="absolute -left-[25px] top-1 size-2 rounded-full bg-blue-600"></span><p class="text-sm font-medium">Order placed</p><p class="text-xs text-slate-500">{{ ($order->placed_at ?? $order->created_at)->format('M j, Y g:i A') }}</p></li>@foreach($order->payments as $payment)<li class="relative"><span class="absolute -left-[25px] top-1 size-2 rounded-full bg-emerald-500"></span><p class="text-sm font-medium">Payment {{ Str::headline($payment->status->value ?? $payment->status) }}</p><p class="text-xs text-slate-500">{{ $payment->created_at?->format('M j, Y g:i A') }}</p></li>@endforeach @foreach($order->refunds as $refund)<li class="relative"><span class="absolute -left-[25px] top-1 size-2 rounded-full bg-red-500"></span><p class="text-sm font-medium">Refund {{ Str::headline($refund->status->value ?? $refund->status) }}</p><p class="text-xs text-slate-500"><x-admin.money :amount="$refund->amount" :currency="$order->currency" /> · {{ $refund->created_at?->format('M j, Y g:i A') }}</p></li>@endforeach</ol></x-admin.card>
        </div>

        <div class="space-y-6 xl:sticky xl:top-24">
            <x-admin.card title="Customer"><p class="font-medium">{{ $order->customer?->name ?: 'Guest' }}</p><p class="mt-1 text-sm text-slate-500">{{ $order->email }}</p>@if($order->customer)<flux:button href="{{ url('/admin/customers/'.$order->customer_id) }}" wire:navigate variant="ghost" size="sm" class="mt-3">View customer</flux:button>@endif</x-admin.card>
            <x-admin.card title="Shipping address"><address class="space-y-1 text-sm not-italic text-slate-600 dark:text-slate-300">@foreach($addressLines((array)$order->shipping_address_json) as $line)<p>{{ $line }}</p>@endforeach</address></x-admin.card>
            <x-admin.card title="Billing address"><address class="space-y-1 text-sm not-italic text-slate-600 dark:text-slate-300">@foreach($addressLines((array)$order->billing_address_json) as $line)<p>{{ $line }}</p>@endforeach</address></x-admin.card>
        </div>
    </div>

    <flux:modal name="create-fulfillment" class="max-w-2xl"><form wire:submit="createFulfillment" class="space-y-6"><div><flux:heading size="lg">Create fulfillment</flux:heading><flux:text class="mt-2">Choose the quantities to ship now.</flux:text></div><div class="space-y-3">@foreach($order->lines as $line)@php $remaining = max(0, $line->quantity - $line->fulfillmentLines->sum('quantity')); @endphp @if($remaining > 0)<div class="grid items-center gap-3 rounded-xl border border-slate-200 p-3 sm:grid-cols-[1fr_8rem] dark:border-slate-700"><div><p class="text-sm font-medium">{{ $line->title_snapshot }}</p><p class="text-xs text-slate-500">{{ $remaining }} available to fulfill</p></div><flux:input wire:model="fulfillmentLines.{{ $line->id }}" type="number" min="0" max="{{ $remaining }}" label="Quantity" /></div>@endif @endforeach</div><div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="trackingCompany" label="Carrier" placeholder="DHL" /><flux:input wire:model="trackingNumber" label="Tracking number" /><div class="sm:col-span-2"><flux:input wire:model="trackingUrl" type="url" label="Tracking URL" /></div></div><div class="flex justify-end gap-2"><flux:modal.close><flux:button type="button" variant="ghost">Cancel</flux:button></flux:modal.close><flux:button type="submit" variant="primary" wire:loading.attr="disabled">Create fulfillment</flux:button></div></form></flux:modal>

    <flux:modal name="create-refund" class="max-w-2xl"><form wire:submit="createRefund" class="space-y-6"><div><flux:heading size="lg">Refund order</flux:heading><flux:text class="mt-2">Refund a custom amount and optionally restock selected quantities.</flux:text></div><flux:input wire:model="refundAmount" type="number" min="1" label="Refund amount (minor units)" required /><div class="space-y-3">@foreach($order->lines as $line)<div class="grid items-center gap-3 rounded-xl border border-slate-200 p-3 sm:grid-cols-[1fr_8rem] dark:border-slate-700"><div><p class="text-sm font-medium">{{ $line->title_snapshot }}</p><p class="text-xs text-slate-500">Select a quantity to restock</p></div><flux:input wire:model="refundLines.{{ $line->id }}" type="number" min="0" max="{{ $line->quantity }}" label="Restock" /></div>@endforeach</div><flux:textarea wire:model="refundReason" label="Reason" rows="3" /><div class="flex justify-end gap-2"><flux:modal.close><flux:button type="button" variant="ghost">Cancel</flux:button></flux:modal.close><flux:button type="submit" variant="danger" wire:loading.attr="disabled">Create refund</flux:button></div></form></flux:modal>
</div>
