<div class="space-y-6">
    <x-admin.page-header title="Analytics" description="Understand sales, conversion, and storefront traffic."><x-slot:actions><flux:button type="button" wire:click="exportCsv" icon="arrow-down-tray" wire:loading.attr="disabled">Export CSV</flux:button>@if($exportUrl)<a href="{{ $exportUrl }}" download="analytics.csv" class="text-sm font-medium text-blue-700 underline">Download export</a>@endif</x-slot:actions></x-admin.page-header>
    <x-admin.card :padding="false"><div class="grid gap-4 p-4 sm:grid-cols-3"><flux:select wire:model.live="dateRange" label="Date range"><flux:select.option value="today">Today</flux:select.option><flux:select.option value="7_days">Last 7 days</flux:select.option><flux:select.option value="30_days">Last 30 days</flux:select.option><flux:select.option value="custom">Custom</flux:select.option></flux:select><flux:select wire:model.live="channelFilter" label="Channel"><flux:select.option value="all">All</flux:select.option><flux:select.option value="storefront">Storefront</flux:select.option><flux:select.option value="api">API</flux:select.option></flux:select><flux:select wire:model.live="deviceFilter" label="Device"><flux:select.option value="all">All</flux:select.option><flux:select.option value="desktop">Desktop</flux:select.option><flux:select.option value="mobile">Mobile</flux:select.option><flux:select.option value="tablet">Tablet</flux:select.option></flux:select>@if($dateRange === 'custom')<flux:input wire:model.live="customStartDate" type="date" label="Start date" /><flux:input wire:model.live="customEndDate" type="date" label="End date" />@endif</div></x-admin.card>
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Key performance indicators"><x-admin.card title="Revenue"><p class="text-3xl font-semibold"><x-admin.money :amount="$totalSales" :currency="$adminStore->default_currency" /></p></x-admin.card><x-admin.card title="Orders"><p class="text-3xl font-semibold tabular-nums">{{ number_format($ordersCount) }}</p></x-admin.card><x-admin.card title="Average order value"><p class="text-3xl font-semibold"><x-admin.money :amount="$averageOrderValue" :currency="$adminStore->default_currency" /></p></x-admin.card><x-admin.card title="Conversion rate"><p class="text-3xl font-semibold tabular-nums">{{ number_format($conversionRate, 2) }}%</p></x-admin.card></section>
    <x-admin.card title="Sales over time"><div class="flex h-56 items-end gap-1 overflow-x-auto" aria-label="Daily revenue chart">@php $max=max(1,collect($salesChartData)->max('revenue') ?? 1); @endphp @forelse($salesChartData as $point)<div class="group flex min-w-5 flex-1 flex-col items-center justify-end" title="{{ $point['date'] }}: {{ $point['revenue'] }}"><div class="w-full rounded-t bg-blue-500" style="height: {{ max(3,round(($point['revenue']/$max)*190)) }}px"></div><span class="mt-2 hidden text-[10px] text-zinc-500 sm:block">{{ substr($point['date'],5) }}</span></div>@empty<p class="m-auto text-sm text-zinc-500">No sales data for this period.</p>@endforelse</div></x-admin.card>
    <div class="grid gap-6 xl:grid-cols-2"><x-admin.card title="Conversion funnel"><dl class="space-y-4"><div class="flex justify-between"><dt>Visits</dt><dd class="font-semibold tabular-nums">{{ number_format($visitsCount) }}</dd></div><div class="flex justify-between"><dt>Add to cart</dt><dd class="font-semibold tabular-nums">{{ number_format($addToCartCount) }}</dd></div><div class="flex justify-between"><dt>Checkout started</dt><dd class="font-semibold tabular-nums">{{ number_format($checkoutStartedCount) }}</dd></div><div class="flex justify-between"><dt>Orders</dt><dd class="font-semibold tabular-nums">{{ number_format($ordersCount) }}</dd></div></dl></x-admin.card><x-admin.card title="Top referrers"><div class="space-y-3">@forelse($topReferrers as $source)<div class="grid grid-cols-[1fr_auto_auto] gap-4 text-sm"><span>{{ $source['source'] }}</span><span>{{ $source['sessions'] }} sessions</span><span>{{ $source['conversion'] }}%</span></div>@empty<p class="text-sm text-zinc-500">No referrer data yet.</p>@endforelse</div></x-admin.card></div>
    <x-admin.card title="Top products">
        <x-admin.table-shell caption="Top products">
            <x-slot:head><tr><th>Rank</th><th>Product</th><th>Units sold</th><th>Revenue</th><th>Share</th></tr></x-slot:head>
            @forelse($topProducts as $index => $product)
                <tr><td>{{ $index + 1 }}</td><td class="font-medium">{{ $product['title'] }}</td><td>{{ $product['units'] }}</td><td><x-admin.money :amount="$product['revenue']" :currency="$adminStore->default_currency" /></td><td>{{ $product['percentage'] }}%</td></tr>
            @empty
                <x-admin.table-empty colspan="5" title="No product sales in this period" />
            @endforelse
        </x-admin.table-shell>
    </x-admin.card>
</div>
