<?php

namespace App\Models;

use App\Enums\MediaStatus;
use App\Enums\MediaType;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Storage;

class ProductMedia extends Model
{
    /** @use HasFactory<\Database\Factories\ProductMediaFactory> */
    use HasFactory;

    /**
     * The table only has a created_at column.
     *
     * @var string|null
     */
    const UPDATED_AT = null;

    /**
     * Processed derivative sizes generated by ProcessMediaUpload.
     *
     * @var list<string>
     */
    const SIZES = ['thumbnail', 'small', 'medium', 'large'];

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'product_id',
        'type',
        'storage_key',
        'alt_text',
        'width',
        'height',
        'mime_type',
        'byte_size',
        'position',
        'status',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'type' => MediaType::class,
            'status' => MediaStatus::class,
            'created_at' => 'datetime',
        ];
    }

    /**
     * Register model event hooks.
     */
    protected static function booted(): void
    {
        // Remove all files (original plus every processed size) from storage.
        static::deleted(function (ProductMedia $media): void {
            $disk = Storage::disk('public');

            $disk->delete($media->storage_key);

            foreach (self::SIZES as $size) {
                $disk->delete($media->pathFor($size));
            }
        });
    }

    /**
     * Get the product that owns the media.
     *
     * @return BelongsTo<Product, $this>
     */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /**
     * Storage path of a processed derivative: media/{product_id}/{media_id}/{size}.{ext}
     */
    public function pathFor(string $size): string
    {
        $extension = pathinfo($this->storage_key, PATHINFO_EXTENSION);

        return "media/{$this->product_id}/{$this->id}/{$size}.{$extension}";
    }

    /**
     * Public URL of the original file.
     */
    public function url(): string
    {
        return Storage::disk('public')->url($this->storage_key);
    }

    /**
     * Public URL of a processed derivative size.
     */
    public function urlFor(string $size): string
    {
        return Storage::disk('public')->url($this->pathFor($size));
    }
}
