<x-admin.page :title="$collectionId ? $title : 'Add collection'" subtitle="Curate products and storefront organization.">
    <x-slot:actions><flux:button wire:click="save" variant="primary" icon="check">Save collection</flux:button></x-slot:actions>
    <form wire:submit="save" class="grid gap-6 xl:grid-cols-3">
        <div class="space-y-6 xl:col-span-2">
            <x-admin.panel heading="Collection details"><div class="space-y-4"><flux:input wire:model.live="title" label="Title" /><flux:input wire:model="handle" label="URL handle" prefix="/collections/" /><flux:textarea wire:model="descriptionHtml" label="Description" rows="6" /><flux:error name="title" /><flux:error name="handle" /></div></x-admin.panel>
            <x-admin.panel heading="Products"><div class="space-y-4"><flux:input wire:model.live.debounce.300ms="productSearch" icon="magnifying-glass" placeholder="Search products…" aria-label="Search products to assign" />@if($this->searchResults->isNotEmpty())<div class="rounded-xl border border-zinc-200 p-2 dark:border-zinc-800">@foreach($this->searchResults as $product)<div wire:key="search-product-{{ $product->id }}" class="flex items-center justify-between gap-3 rounded-lg p-2 hover:bg-zinc-50 dark:hover:bg-zinc-800"><span>{{ $product->title }}</span><flux:button type="button" wire:click="addProduct({{ $product->id }})" size="sm" icon="plus">Add</flux:button></div>@endforeach</div>@endif<div class="grid gap-2">@forelse($this->assignedProducts as $product)<div wire:key="assigned-product-{{ $product->id }}" class="flex items-center gap-3 rounded-xl border border-zinc-200 p-3 dark:border-zinc-800"><flux:icon.bars-3 class="size-5 text-zinc-400" /><span class="flex-1 font-medium">{{ $product->title }}</span><flux:button type="button" wire:click="removeProduct({{ $product->id }})" variant="ghost" icon="x-mark" aria-label="Remove {{ $product->title }}" /></div>@empty<flux:text>No products assigned.</flux:text>@endforelse</div></div></x-admin.panel>
        </div>
        <x-admin.panel heading="Publishing" class="h-fit"><flux:select wire:model="status" label="Status"><flux:select.option value="active">Active</flux:select.option><flux:select.option value="draft">Draft</flux:select.option><flux:select.option value="archived">Archived</flux:select.option></flux:select></x-admin.panel>
        <div class="sticky bottom-0 z-20 flex justify-end gap-2 border-t border-zinc-200 bg-white/95 p-4 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/95 xl:col-span-3"><flux:button href="/admin/collections" wire:navigate>Discard</flux:button><flux:button type="submit" variant="primary">Save</flux:button></div>
    </form>
</x-admin.page>
