<div x-data="{ open: @entangle('open').live, active: -1, trigger: null }" x-init="$watch('open', value => { document.documentElement.classList.toggle('overflow-hidden', value); if (value) { trigger = document.activeElement; $nextTick(() => $refs.search?.focus()) } else { trigger?.focus?.(); active = -1 } })" @keydown.escape.window="open = false">
    <div x-show="open" x-cloak class="fixed inset-0 z-[80] overflow-y-auto p-4 sm:p-8" role="dialog" aria-modal="true" aria-label="Search">
        <button class="fixed inset-0 bg-slate-950/60 backdrop-blur-sm" @click="open = false" aria-label="Close search"></button>
        <section class="relative mx-auto mt-[8vh] max-w-2xl overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-slate-950" @click.stop @keydown.arrow-down.prevent="const items=[...$el.querySelectorAll('[data-search-result]')]; if(items.length){ active=(active+1)%items.length; items[active].focus(); }" @keydown.arrow-up.prevent="const items=[...$el.querySelectorAll('[data-search-result]')]; if(items.length){ active=(active<=0?items.length:active)-1; items[active].focus(); }" @keydown.tab="const items=[...$el.querySelectorAll('button:not([disabled]),a[href],input:not([disabled])')]; if(!items.length)return; if($event.shiftKey && document.activeElement===items[0]){$event.preventDefault();items[items.length-1].focus()}else if(!$event.shiftKey && document.activeElement===items[items.length-1]){$event.preventDefault();items[0].focus()}">
            <form wire:submit="goToResults" class="flex items-center gap-3 border-b border-slate-200 p-4 dark:border-slate-800"><svg aria-hidden="true" class="size-5 shrink-0 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="7" stroke-width="1.7"/><path d="m20 20-4-4" stroke-width="1.7"/></svg><label class="min-w-0 flex-1"><span class="sr-only">Search products and collections</span><input x-ref="search" type="search" wire:model.live.debounce.300ms="query" class="w-full border-0 bg-transparent p-2 text-lg outline-none placeholder:text-slate-400 focus:ring-0" placeholder="Search products and collections" autocomplete="off" role="combobox" aria-controls="search-results" :aria-expanded="{{ ($products !== [] || $collections !== []) ? 'true' : 'false' }}"></label><button type="button" @click="open = false" class="sf-icon-button" aria-label="Close search">&times;</button></form>
            <div id="search-results" role="listbox" class="max-h-[65vh] overflow-y-auto p-3" wire:loading.class="opacity-50" wire:target="query">
                @if (mb_strlen(trim($query)) < 2)
                    <p class="p-8 text-center text-sm text-slate-500">Type at least two characters to search.</p>
                @elseif ($products === [] && $collections === [])
                    <p class="p-8 text-center text-sm text-slate-500">No results for “{{ $query }}”</p>
                @else
                    @if($products !== [])<h2 class="px-3 pb-2 pt-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Products</h2><div class="space-y-1">@foreach($products as $product)<a data-search-result href="{{ url('/products/'.$product['handle']) }}" wire:navigate @click="open = false" role="option" class="flex min-h-16 items-center gap-3 rounded-xl p-2 hover:bg-slate-100 focus:bg-slate-100 dark:hover:bg-slate-900 dark:focus:bg-slate-900"><div class="size-12 shrink-0 overflow-hidden rounded-lg bg-slate-100 dark:bg-slate-800">@if($product['image'])<img src="{{ Storage::disk('public')->url($product['image']) }}" alt="" class="h-full w-full object-cover">@endif</div><span class="min-w-0 flex-1 truncate font-medium">{{ $product['title'] }}</span><span class="text-sm"><x-storefront.price :amount="$product['price']" :currency="$product['currency']" /></span></a>@endforeach</div>@endif
                    @if($collections !== [])<h2 class="mt-4 px-3 pb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Collections</h2><div class="space-y-1">@foreach($collections as $collection)<a data-search-result href="{{ url('/collections/'.$collection['handle']) }}" wire:navigate @click="open = false" role="option" class="flex min-h-12 items-center justify-between rounded-xl px-3 py-2 font-medium hover:bg-slate-100 dark:hover:bg-slate-900"><span>{{ $collection['title'] }}</span><span aria-hidden="true">&rarr;</span></a>@endforeach</div>@endif
                    <button wire:click="goToResults" class="mt-4 flex min-h-12 w-full items-center justify-center rounded-xl border-t border-slate-200 px-3 text-sm font-semibold text-blue-700 hover:bg-blue-50 dark:border-slate-800 dark:text-blue-300 dark:hover:bg-blue-950/40">View all results <span aria-hidden="true" class="ml-1">&rarr;</span></button>
                @endif
            </div>
        </section>
    </div>
</div>
