<div x-data="{ open: @entangle('open') }" x-cloak x-effect="document.body.classList.toggle('overflow-hidden', open)" @keydown.escape.window="open = false" @open-cart-drawer.window="open = true" class="relative z-50">
    <div x-show="open" x-transition.opacity class="fixed inset-0 bg-black/40" aria-hidden="true" wire:click="close"></div>
    <aside x-show="open" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="translate-x-0" x-transition:leave-end="translate-x-full" class="fixed inset-y-0 right-0 flex w-full max-w-md flex-col bg-white p-6 shadow-2xl dark:bg-zinc-900" role="dialog" aria-modal="true" aria-label="Shopping cart">
        <div class="flex items-center justify-between"><h2 class="text-xl font-semibold">Your cart</h2><button type="button" class="rounded-full border px-3 py-2" wire:click="close" aria-label="Close cart">Close</button></div>
        @if($cart->lines->isEmpty())<div class="flex flex-1 items-center justify-center text-center"><div><p class="text-lg font-semibold">Your cart is empty</p><a class="mt-4 inline-block text-blue-600 underline" href="{{ route('collections.index') }}" wire:navigate wire:click="close">Browse collections</a></div></div>@else
            <div class="mt-6 flex-1 divide-y divide-zinc-200 overflow-y-auto dark:divide-zinc-700">@foreach($cart->lines as $line)<div class="flex gap-3 py-4" wire:key="drawer-line-{{ $line->id }}"><div class="flex h-16 w-16 shrink-0 items-center justify-center rounded-lg bg-zinc-100 text-xl dark:bg-zinc-800">⌂</div><div class="min-w-0 flex-1"><a class="font-medium" href="{{ route('product.show', $line->variant->product->handle) }}" wire:navigate wire:click="close">{{ $line->variant->product->title }}</a><p class="text-sm text-zinc-500">{{ $line->variant->title }}</p><div class="mt-2 flex items-center gap-2"><button type="button" wire:click="decrease({{ $line->id }})" class="h-8 w-8 rounded-full border" aria-label="Decrease quantity">−</button><span class="min-w-5 text-center" aria-live="polite">{{ $line->quantity }}</span><button type="button" wire:click="increase({{ $line->id }})" class="h-8 w-8 rounded-full border" aria-label="Increase quantity">+</button><button type="button" wire:click="remove({{ $line->id }})" class="ml-auto text-xs text-red-600 underline">Remove</button></div></div><p class="text-sm font-semibold">{{ $this->formatMoney($line->line_total_amount) }}</p></div>@endforeach</div>
            @error('cart')<p class="mt-3 text-sm text-red-600" role="alert">{{ $message }}</p>@enderror
            @error('discountCode')<p class="mt-3 text-sm text-red-600" role="alert">{{ $message }}</p>@enderror
            @if($message)<p class="mt-3 text-sm text-green-700" role="status">{{ $message }}</p>@endif
            <div class="border-t border-zinc-200 pt-5 dark:border-zinc-700"><form wire:submit="applyDiscount" class="flex gap-2"><label class="sr-only" for="drawer-discount">Discount code</label><input id="drawer-discount" type="text" wire:model.blur="discountCode" placeholder="Discount code" class="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm dark:bg-zinc-950"><button class="rounded-lg border px-3 py-2 text-sm font-semibold">Apply</button></form><dl class="mt-4 space-y-2 text-sm"><div class="flex justify-between"><dt>Subtotal</dt><dd>{{ $this->formatMoney($cart->subtotalAmount()) }}</dd></div>@if($discountAmount > 0)<div class="flex justify-between text-green-700"><dt>Discount</dt><dd>-{{ $this->formatMoney($discountAmount) }}</dd></div>@endif<div class="flex justify-between font-semibold"><dt>Total before shipping</dt><dd>{{ $this->formatMoney(max(0, $cart->subtotalAmount() - $discountAmount)) }}</dd></div></dl><button type="button" wire:click="checkout" wire:loading.attr="disabled" class="mt-4 block w-full rounded-full bg-blue-600 px-5 py-3 text-center font-semibold text-white"><span wire:loading.remove wire:target="checkout">Checkout</span><span wire:loading wire:target="checkout">Starting checkout…</span></button><a href="{{ route('cart.show') }}" wire:navigate wire:click="close" class="mt-3 block w-full rounded-full border px-5 py-3 text-center font-semibold">View cart</a></div>
        @endif
    </aside>
</div>
